In [3]:
import tensorflow as tf

In [4]:
hello=tf.constant('Hello, Tensorflow')
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [5]:
a=tf.constant(10)
b=tf.constant(32)
c=tf.add(a,b)
print(c)

Tensor("Add:0", shape=(), dtype=int32)


In [7]:
sess=tf.Session()
print(sess.run(hello))
print(sess.run([a,b,c]))
sess.close()

b'Hello, Tensorflow'
[10, 32, 42]


# 3.2 PlaceHolder

In [8]:
X=tf.placeholder(tf.float32, [None,3])
print(X)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)


In [11]:
x_data=[[1,2,3],[4,5,6]]

W=tf.Variable(tf.random_normal([3,2]))
b=tf.Variable(tf.random_normal([2,1]))

#W=tf.Variable([[.1,.1],[.2,.2],[.3,.3]])

expr=tf.matmul(X,W)+b

sess=tf.Session()
sess.run(tf.global_variables_initializer())

print(x_data)
print('W : \n', sess.run(W))
print('b : \n', sess.run(b))
print('expr :\n',sess.run(expr, feed_dict={X:x_data}))
sess.close()

[[1, 2, 3], [4, 5, 6]]
W : 
 [[ 1.0313114  -0.87785816]
 [ 0.05046078 -1.1747489 ]
 [ 1.6255963  -0.4801863 ]]
b : 
 [[-0.8043297]
 [-1.0051572]]
expr :
 [[  5.204692   -5.4722447]
 [ 13.125971  -13.271453 ]]


# 3.3 Linear Regression Model

In [12]:
x_data=[1,2,3]
y_data=[1,2,3]

W=tf.Variable(tf.random_uniform([1],-1.,1.))
b=tf.Variable(tf.random_uniform([1],-1.,1.))

In [14]:
"""
X=tf.placeholder(tf.float32)
Y=tf.placeholder(tf.float32)
print(X)
print(Y)
"""

Tensor("Placeholder_1:0", dtype=float32)
Tensor("Placeholder_2:0", dtype=float32)


In [15]:
X=tf.placeholder(tf.float32, name='X')
Y=tf.placeholder(tf.float32, name='Y')
print(X)
print(Y)

Tensor("X_1:0", dtype=float32)
Tensor("Y_1:0", dtype=float32)


In [16]:
hypothesis=W*X+b
cost=tf.reduce_mean(tf.square(hypothesis-Y)) #MSE
optimizer=tf.train.GradientDescentOptimizer(learning_rate=.1)
train_op=optimizer.minimize(cost)

In [22]:
# 그래프 실행
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(100):
        _, cost_val = sess.run([train_op,cost], feed_dict={X:x_data, Y:y_data})
        #print(step,'\t cost :',cost_val,'\t W:',sess.run(W),'\t b:',sess.run(b))
    
    print('X:5,Y:',sess.run(hypothesis, feed_dict={X:5}))
    print('X:2.5,Y:',sess.run(hypothesis, feed_dict={X:2.5}))

X:5,Y: [5.0588946]
X:2.5,Y: [2.5048978]
