# 1) List -> np.array

In [3]:
import numpy as np
lst = [1, 2, 3, 4]
print(type(lst))
arr1 = np.array(lst, np.int)
print(arr1)
arr2 = np.array(lst, np.str)
print(arr2)
arr3 = np.array(lst, np.float)
print(arr3)
print(type(arr3))

<class 'list'>
[1 2 3 4]
['1' '2' '3' '4']
[1. 2. 3. 4.]
<class 'numpy.ndarray'>


# 2) ndarray.ndim

In [4]:
import numpy as np
arr = np.array(5)
print(arr)
print(arr.ndim)

5
0


In [5]:
lst = [1, 2, 3, 4]
arr = np.array(lst)
print(arr)
print(arr.ndim)

[1 2 3 4]
1


In [6]:
lst = [[1, 2], [3, 4]]
arr = np.array(lst)
print(arr)
print(arr.ndim)

[[1 2]
 [3 4]]
2


# 3) ndarray.shape, size, dtype

In [8]:
import numpy as np
arr = np.zeros((3, 5, 2), dtype=np.int)
print("shape: ", arr.shape)
print("size: ", arr.size)
print("dtype: ", arr.dtype)
print("arr: ", arr)

shape:  (3, 5, 2)
size:  30
dtype:  int32
arr:  [[[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]]


# 4) Reshape

In [13]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print("origin: ", arr)
arr = arr.reshape(2, 2)
print("after: ", arr)
arr = arr.reshape(1, 4)
print("after2: ", arr)
arr = arr.reshape(-1, 2)
print("after2: ", arr)

origin:  [1 2 3 4]
after:  [[1 2]
 [3 4]]
after2:  [[1 2 3 4]]
after2:  [[1 2]
 [3 4]]


# 5) Rank

In [14]:
import numpy as np
s = 483
print("Rank 0. Scalar = ", s)

Rank 0. Scalar =  483


In [15]:
v = np.array([1.1, 2.2, 3.3])  # Vector
print("Rank 1. Shape = ", v.shape)
print("Rank 1. Items = \n", v)

Rank 1. Shape =  (3,)
Rank 1. Items = 
 [1.1 2.2 3.3]


In [16]:
m = np.array([[1, 2, 3], [4, 5, 6]])  # Matrix
print("Rank 2. Shape = ", m.shape)
print("Rank 2. Items = \n", m)

Rank 2. Shape =  (2, 3)
Rank 2. Items = 
 [[1 2 3]
 [4 5 6]]


In [17]:
t = np.array([[[2], [4], [6]], [[8], [10], [12]],
             [[14], [16], [18]], [[20], [22], [24]]]) # 3-Tensor
print("Rank 3. Shape = ", t.shape)
print("Rank 3. Items = \n", t)

Rank 3. Shape =  (4, 3, 1)
Rank 3. Items = 
 [[[ 2]
  [ 4]
  [ 6]]

 [[ 8]
  [10]
  [12]]

 [[14]
  [16]
  [18]]

 [[20]
  [22]
  [24]]]


In [18]:
t = np.array([[[2, 1], [4, 1], [6, 1]], [[8, 1], [10, 1], [12, 1]],
             [[14, 1], [16, 1], [18, 1]], [[20, 1], [22, 1], [24, 1]]]) # 3-Tensor
print("Rank 3. (2nd) Shape = ", t.shape)
print("Rank 3. (2nd) Items = \n", t)

Rank 3. (2nd) Shape =  (4, 3, 2)
Rank 3. (2nd) Items = 
 [[[ 2  1]
  [ 4  1]
  [ 6  1]]

 [[ 8  1]
  [10  1]
  [12  1]]

 [[14  1]
  [16  1]
  [18  1]]

 [[20  1]
  [22  1]
  [24  1]]]


In [19]:
# array 생성과 기본값 채우기
import numpy as np

# 0으로 채운 배열 생성
a = np.zeros((3, 2))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [20]:
# 1로 채운 배열 생성
b = np.ones((4, 2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [21]:
# 지정한 숫자로 채우기
c = np.full((2, 3), 7)
print(c)

[[7 7 7]
 [7 7 7]]


In [22]:
# 대각선만 1인 행렬
d = np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [23]:
# 0 ~ 1사이의 난수
e = np.random.random((2, 2))
print(e)

[[0.57800554 0.41122284]
 [0.94363894 0.69566411]]


In [24]:
# array 연산
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

print(a+b)
print(b-a)
print(a*b)
print(a/b)
print(a@b)   # 행렬곱셈

[[ 6  8]
 [10 12]]
[[4 4]
 [4 4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19 22]
 [43 50]]


In [25]:
x = float('nan')
print(np.isnan(x))

True
