In [41]:
import numpy as np
import pandas as pd
list_of_ints=[1,2,3]
Array_1=np.array(list_of_ints)
Array_1

array([1, 2, 3])

In [7]:
Array_1[1], type(Array_1), Array_1.dtype

(2, numpy.ndarray, dtype('int32'))

In [8]:
Array_1.nbytes

12

In [9]:
Array_1=np.array(list_of_ints, dtype='int8')

In [10]:
Array_1.nbytes

3

In [14]:
Array_1b=Array_1.astype('float32')
Array_1b.nbytes

12

In [18]:
complex_list=[1,2,3]+[1.,2.,3.]+['a','b','c']
Array_2=np.array(complex_list[:3])
print(Array_2.dtype)
Array_2=np.array(complex_list[:6])
print(Array_2.dtype)
Array_2=np.array(complex_list)
print(Array_2.dtype)

int32
float64
<U32


In [19]:
a_list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
Array_2D=np.array(a_list_of_lists)
Array_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
original_array=np.array([1,2,3,4,5,6,7,8])
original_array.resize(4,2)
original_array

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [23]:
original_array.T

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [24]:
original_value=np.arange(9).reshape(3,3)
original_value

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
np.arange(9)[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [26]:
np.random.randint(1,10,(3,3))

array([[3, 5, 8],
       [5, 7, 5],
       [1, 7, 8]])

In [31]:
fractions=np.linspace(0,1,20)[::-1]
fractions

array([1.        , 0.94736842, 0.89473684, 0.84210526, 0.78947368,
       0.73684211, 0.68421053, 0.63157895, 0.57894737, 0.52631579,
       0.47368421, 0.42105263, 0.36842105, 0.31578947, 0.26315789,
       0.21052632, 0.15789474, 0.10526316, 0.05263158, 0.        ])

In [33]:
growth=np.logspace(0,1,10,10)
growth

array([ 1.        ,  1.29154967,  1.66810054,  2.15443469,  2.7825594 ,
        3.59381366,  4.64158883,  5.9948425 ,  7.74263683, 10.        ])

In [37]:
std_gaussian=np.random.normal(size=(3,3))
std_gaussian

array([[ 0.50789528,  0.93339356,  1.9089364 ],
       [ 1.06150842, -0.52570415, -1.03136305],
       [-0.05201209, -2.8953487 ,  0.81627257]])

In [39]:
gaussian=np.random.normal(1,3,size=(3,3))
gaussian

array([[-1.39945056, -0.14727115, -2.35927171],
       [ 2.10235257, -1.94348935, -0.05889509],
       [-3.62122802,  0.29185272,  0.1115944 ]])

In [40]:
housing=np.loadtxt('C:\\Users\\la\\Desktop\\PythonDataScienceEssentials - SecondEdition_Code\\Chapter 2\\code\\regression-datasets-housing.csv',
                  delimiter=',',dtype=float)


In [42]:
housing_filename='C:\\Users\\la\\Desktop\\PythonDataScienceEssentials - SecondEdition_Code\\Chapter 2\\code\\regression-datasets-housing.csv'
housing=pd.read_csv(housing_filename,header=None)

In [44]:
housing_array=housing.values
housing_array.dtype

dtype('float64')

In [47]:
housing.dtypes

0     float64
1       int64
2     float64
3       int64
4     float64
5     float64
6     float64
7     float64
8       int64
9       int64
10      int64
11    float64
12    float64
13    float64
dtype: object

In [53]:
a=np.arange(5).reshape(1,5)
a+=1
a=a*a
a

array([[ 1,  4,  9, 16, 25]])