In [1]:
import pandas as pd

In [6]:
categorical_feature=pd.Series(['sunny','cloudy','snowy','rainy','foggy' ])
mapping = pd.get_dummies(categorical_feature)
mapping

cloudy  foggy  rainy  snowy  sunny
0       0      0      0      0      1
1       1      0      0      0      0
2       0      0      0      1      0
3       0      0      1      0      0
4       0      1      0      0      0

In [7]:
mapping['sunny']

0    1
1    0
2    0
3    0
4    0
Name: sunny, dtype: uint8

In [11]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
ohe=OneHotEncoder()
levels=['sunny','cloudy','snowy','rainy','foggy' ]
fit_levs=le.fit_transform(levels)
fit_levs

array([4, 0, 3, 2, 1], dtype=int64)

In [15]:
ohe.fit([[fit_levs[0]],[fit_levs[1]],[fit_levs[2]],[fit_levs[3]],[fit_levs[4]]])
print(ohe.transform([le.transform(['sunny'])]).toarray())
print(ohe.transform([le.transform(['cloudy'])]).toarray())

[[0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]]


In [16]:
ohe

OneHotEncoder(categorical_features='all', dtype=<class 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=True)