In [1]:
import numpy as np
a=np.arange(5).reshape(1,5)+1
b=np.arange(5).reshape(5,1)+1
a*b

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [6]:
a2=np.array([1,2,3,4,5]*5).reshape(5,5)
b2=a2.T
a2,b2,a2*b2

(array([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]), array([[1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5]]), array([[ 1,  2,  3,  4,  5],
        [ 2,  4,  6,  8, 10],
        [ 3,  6,  9, 12, 15],
        [ 4,  8, 12, 16, 20],
        [ 5, 10, 15, 20, 25]]))

In [7]:
np.sum(a2,axis=0)

array([ 5, 10, 15, 20, 25])

In [8]:
np.sum(a2,axis=1)

array([15, 15, 15, 15, 15])

In [11]:
np.exp(a2)

array([[  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
        148.4131591 ],
       [  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
        148.4131591 ],
       [  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
        148.4131591 ],
       [  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
        148.4131591 ],
       [  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
        148.4131591 ]])

In [16]:
%timeit -n 1 -r 4 [i+1.0 for i in range(10**6)]
%timeit -n 1 -r 4 np.arange(10**6)+1.


91 ms ± 2.83 ms per loop (mean ± std. dev. of 4 runs, 1 loop each)
4.61 ms ± 137 µs per loop (mean ± std. dev. of 4 runs, 1 loop each)


In [18]:
import math
%timeit -n 1 -r 3 [math.sqrt(i) for i in range(10**6)]
%timeit -n 1 -r 3 np.sqrt(np.arange(10**6)) 

159 ms ± 2.66 ms per loop (mean ± std. dev. of 3 runs, 1 loop each)
5.05 ms ± 137 µs per loop (mean ± std. dev. of 3 runs, 1 loop each)


In [23]:
M=np.arange(5*5, dtype=float).reshape(5,5)

In [21]:
coefs=np.array([1.,0.5,0.5,0.5,0.5])
coefs_matrix=np.column_stack((coefs,coefs[::-1]))
print(coefs_matrix)

[[1.  0.5]
 [0.5 0.5]
 [0.5 0.5]
 [0.5 0.5]
 [0.5 1. ]]


In [24]:
np.dot(M,coefs)

array([ 5., 20., 35., 50., 65.])

In [25]:
np.dot(coefs,M)

array([25., 28., 31., 34., 37.])

In [26]:
np.dot(M,coefs_matrix)

array([[ 5.,  7.],
       [20., 22.],
       [35., 37.],
       [50., 52.],
       [65., 67.]])

In [27]:
M=np.arange(100, dtype=float).reshape(10,10)
M[2:9:2,:]

array([[20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.],
       [80., 81., 82., 83., 84., 85., 86., 87., 88., 89.]])

In [28]:
M[2:9:2,5:]

array([[25., 26., 27., 28., 29.],
       [45., 46., 47., 48., 49.],
       [65., 66., 67., 68., 69.],
       [85., 86., 87., 88., 89.]])

In [32]:
M[2:9:2,5::-1]

array([[25., 24., 23., 22., 21., 20.],
       [45., 44., 43., 42., 41., 40.],
       [65., 64., 63., 62., 61., 60.],
       [85., 84., 83., 82., 81., 80.]])

In [33]:
row_index=(M[:,0]>=20) & (M[:,0]<=80)
col_index=M[0,:]>=5
row_index,col_index

(array([False, False,  True,  True,  True,  True,  True,  True,  True,
        False]),
 array([False, False, False, False, False,  True,  True,  True,  True,
         True]))

In [34]:
M[row_index,:]

array([[20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
       [50., 51., 52., 53., 54., 55., 56., 57., 58., 59.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.],
       [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
       [80., 81., 82., 83., 84., 85., 86., 87., 88., 89.]])

In [35]:
M[row_index,:][:,col_index]

array([[25., 26., 27., 28., 29.],
       [35., 36., 37., 38., 39.],
       [45., 46., 47., 48., 49.],
       [55., 56., 57., 58., 59.],
       [65., 66., 67., 68., 69.],
       [75., 76., 77., 78., 79.],
       [85., 86., 87., 88., 89.]])

In [36]:
M[:,col_index]

array([[ 5.,  6.,  7.,  8.,  9.],
       [15., 16., 17., 18., 19.],
       [25., 26., 27., 28., 29.],
       [35., 36., 37., 38., 39.],
       [45., 46., 47., 48., 49.],
       [55., 56., 57., 58., 59.],
       [65., 66., 67., 68., 69.],
       [75., 76., 77., 78., 79.],
       [85., 86., 87., 88., 89.],
       [95., 96., 97., 98., 99.]])

In [51]:
mask=(M>=20) & (M<=90) &((M/10.) %1 >=0.5)
M[mask]

array([25., 26., 27., 28., 29., 35., 36., 37., 38., 39., 45., 46., 47.,
       48., 49., 55., 56., 57., 58., 59., 65., 66., 67., 68., 69., 75.,
       76., 77., 78., 79., 85., 86., 87., 88., 89.])

In [52]:
row_index=[1,1,2,7]
col_index=[0,2,4,8]
M[row_index,col_index]

array([10., 12., 24., 78.])

In [53]:
M[row_index,:][:,col_index]

array([[10., 12., 14., 18.],
       [10., 12., 14., 18.],
       [20., 22., 24., 28.],
       [70., 72., 74., 78.]])

In [54]:
N=M[2:9:2,5:].copy()

In [55]:
dataset=np.arange(50).reshape(10,5)
single_line=np.arange(1*5).reshape(1,5)
a_few_line=np.arange(3*5).reshape(3,5)
np.vstack((dataset,single_line))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [ 0,  1,  2,  3,  4]])

In [56]:
np.vstack((dataset,a_few_line))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [57]:
np.vstack((dataset,single_line,single_line))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [ 0,  1,  2,  3,  4],
       [ 0,  1,  2,  3,  4]])

In [62]:
bias=np.ones(10).reshape(10,1)
np.hstack((dataset,bias))

array([[ 0.,  1.,  2.,  3.,  4.,  1.],
       [ 5.,  6.,  7.,  8.,  9.,  1.],
       [10., 11., 12., 13., 14.,  1.],
       [15., 16., 17., 18., 19.,  1.],
       [20., 21., 22., 23., 24.,  1.],
       [25., 26., 27., 28., 29.,  1.],
       [30., 31., 32., 33., 34.,  1.],
       [35., 36., 37., 38., 39.,  1.],
       [40., 41., 42., 43., 44.,  1.],
       [45., 46., 47., 48., 49.,  1.]])

In [63]:
np.column_stack((dataset,bias))


array([[ 0.,  1.,  2.,  3.,  4.,  1.],
       [ 5.,  6.,  7.,  8.,  9.,  1.],
       [10., 11., 12., 13., 14.,  1.],
       [15., 16., 17., 18., 19.,  1.],
       [20., 21., 22., 23., 24.,  1.],
       [25., 26., 27., 28., 29.,  1.],
       [30., 31., 32., 33., 34.,  1.],
       [35., 36., 37., 38., 39.,  1.],
       [40., 41., 42., 43., 44.,  1.],
       [45., 46., 47., 48., 49.,  1.]])

In [66]:
np.dstack((dataset*1,dataset*2,dataset*3))

array([[[  0,   0,   0],
        [  1,   2,   3],
        [  2,   4,   6],
        [  3,   6,   9],
        [  4,   8,  12]],

       [[  5,  10,  15],
        [  6,  12,  18],
        [  7,  14,  21],
        [  8,  16,  24],
        [  9,  18,  27]],

       [[ 10,  20,  30],
        [ 11,  22,  33],
        [ 12,  24,  36],
        [ 13,  26,  39],
        [ 14,  28,  42]],

       [[ 15,  30,  45],
        [ 16,  32,  48],
        [ 17,  34,  51],
        [ 18,  36,  54],
        [ 19,  38,  57]],

       [[ 20,  40,  60],
        [ 21,  42,  63],
        [ 22,  44,  66],
        [ 23,  46,  69],
        [ 24,  48,  72]],

       [[ 25,  50,  75],
        [ 26,  52,  78],
        [ 27,  54,  81],
        [ 28,  56,  84],
        [ 29,  58,  87]],

       [[ 30,  60,  90],
        [ 31,  62,  93],
        [ 32,  64,  96],
        [ 33,  66,  99],
        [ 34,  68, 102]],

       [[ 35,  70, 105],
        [ 36,  72, 108],
        [ 37,  74, 111],
        [ 38,  76, 114],
        [ 3

In [67]:
np.insert(dataset,3,bias,axis=1)

array([[ 0,  1,  2,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  3,  4],
       [ 5,  6,  7,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  8,  9],
       [10, 11, 12,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 13, 14],
       [15, 16, 17,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 18, 19],
       [20, 21, 22,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 23, 24],
       [25, 26, 27,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 28, 29],
       [30, 31, 32,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 33, 34],
       [35, 36, 37,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 38, 39],
       [40, 41, 42,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 43, 44],
       [45, 46, 47,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 48, 49]])

In [72]:
np.insert(dataset,3,dataset.T,axis=1)

array([[ 0,  1,  2,  0,  1,  2,  3,  4,  3,  4],
       [ 5,  6,  7,  5,  6,  7,  8,  9,  8,  9],
       [10, 11, 12, 10, 11, 12, 13, 14, 13, 14],
       [15, 16, 17, 15, 16, 17, 18, 19, 18, 19],
       [20, 21, 22, 20, 21, 22, 23, 24, 23, 24],
       [25, 26, 27, 25, 26, 27, 28, 29, 28, 29],
       [30, 31, 32, 30, 31, 32, 33, 34, 33, 34],
       [35, 36, 37, 35, 36, 37, 38, 39, 38, 39],
       [40, 41, 42, 40, 41, 42, 43, 44, 43, 44],
       [45, 46, 47, 45, 46, 47, 48, 49, 48, 49]])

In [80]:
np.insert(dataset,3,np.ones(10).T,axis=1)

array([[ 0,  1,  2,  1,  3,  4],
       [ 5,  6,  7,  1,  8,  9],
       [10, 11, 12,  1, 13, 14],
       [15, 16, 17,  1, 18, 19],
       [20, 21, 22,  1, 23, 24],
       [25, 26, 27,  1, 28, 29],
       [30, 31, 32,  1, 33, 34],
       [35, 36, 37,  1, 38, 39],
       [40, 41, 42,  1, 43, 44],
       [45, 46, 47,  1, 48, 49]])