In [1]:
import torch

In [2]:
x_train = torch.FloatTensor([[73,80,75],[93,88,93],[89,91,90],[96,98,100],[73,66,70]])
y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])

In [3]:
x_train.shape

torch.Size([5, 3])

# Hypothesis Function : Naive

```python
hypothesis = x1_train*w1 + x2_train*w2 + x3_train*w3 + b
```

# Hypothesis Function : Matrix

```python
hypothesis = x_train.matmul(W) + b
```

# Full Code with torch.optim 1

In [4]:
import torch.optim as optim

In [5]:
x_train = torch.FloatTensor([[73,80,75],[93,88,93],[89,91,90],[96,98,100],[73,66,70]])
y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])

W = torch.zeros((3,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W,b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs+1):
    
    hypothesis = x_train.matmul(W)+b
    
    cost = torch.mean((hypothesis - y_train)**2)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    print('Epoch {:4d}/{} hypothesis: {}, Cost: {:.6f}'.format(epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()))

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]), Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([67.2578, 80.8397, 79.6523, 86.7394, 61.6605]), Cost: 9298.520508
Epoch    2/20 hypothesis: tensor([104.9128, 126.0990, 124.2466, 135.3015,  96.1821]), Cost: 2915.712646
Epoch    3/20 hypothesis: tensor([125.9942, 151.4381, 149.2133, 162.4896, 115.5097]), Cost: 915.040527
Epoch    4/20 hypothesis: tensor([137.7968, 165.6247, 163.1911, 177.7112, 126.3307]), Cost: 287.936005
Epoch    5/20 hypothesis: tensor([144.4044, 173.5674, 171.0168, 186.2332, 132.3891]), Cost: 91.371017
Epoch    6/20 hypothesis: tensor([148.1035, 178.0144, 175.3980, 191.0042, 135.7812]), Cost: 29.758139
Epoch    7/20 hypothesis: tensor([150.1744, 180.5042, 177.8508, 193.6753, 137.6805]), Cost: 10.445305
Epoch    8/20 hypothesis: tensor([151.3336, 181.8983, 179.2240, 195.1707, 138.7440]), Cost: 4.391228
Epoch    9/20 hypothesis: tensor([151.9824, 182.6789, 179.9928, 196.0079, 139.3396]), Cost: 2.493135
Epoch   

In [6]:
hypothesis, hypothesis.shape, hypothesis.squeeze(), hypothesis.squeeze().detach()

(tensor([[152.8020],
         [183.6731],
         [180.9677],
         [197.0699],
         [140.1000]], grad_fn=<AddBackward0>),
 torch.Size([5, 1]),
 tensor([152.8020, 183.6731, 180.9677, 197.0699, 140.1000],
        grad_fn=<SqueezeBackward0>),
 tensor([152.8020, 183.6731, 180.9677, 197.0699, 140.1000]))

In [7]:
 hypothesis.squeeze()[0]

tensor(152.8020, grad_fn=<SelectBackward>)

# nn.Module, Cost : 사용 편리, Debugging 편리

```python
import torch.nn as nn

class MultivariateLinearRegressionModule(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3,1)
        
    def forward(self,x):
        return self.linear(x)

hypothesis = model(x_train)

import torch.nn.functional as F

cost = F.mse_loss(prediction, y_train)
```

# Full Code with torch.optim

```python
x_train = torch.FloatTensor([[73,80,75],[93,88,93],[89,91,90],[96,98,100],[73,66,70]])
y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])

#W = torch.zeros((3,1), requires_grad=True)
#b = torch.zeros(1, requires_grad=True)
model = MultivariateLinearRegressionModule()

optimizer = optim.SGD([W,b], lr=1e-5)
#prediction 정의 필요 5x1

nb_epochs = 20
for epoch in range(nb_epochs+1):
    
    #hypothesis = x_train.matmul(W)+b
    hypothesis = model(x_train)
    
    #cost = torch.mean((hypothesis - y_train)**2)
    cost = F.mse_loss(prediction, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    print('Epoch {:4d}/{} hypothesis: {}, Cost: {:.6f}'.format(epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()))
```