In [1]:
import numpy as np
import torch

# Numpy Review

In [2]:
t = np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print(t.ndim, t.shape)

1 (7,)


In [4]:
print(t[0],t[1],t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


In [5]:
t = np.zeros((4,3))
print(t.shape)
for i in range(12):
    t[i//3][i%3] = i+1
print(t)

(4, 3)
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [6]:
print(t.ndim, t.shape)

2 (4, 3)


In [7]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [8]:
print(t.dim(), t.shape, t.size()) #shape는 가로가 없음 function 기능이 아님
print(t[0],t[1],t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

1 torch.Size([7]) torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [9]:
t = torch.FloatTensor([[ 1.,  2.,  3.], [ 4.,  5.,  6.], [ 7.,  8.,  9.], [10., 11., 12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [10]:
print(t.dim(), t.shape, t.size()) #shape는 가로가 없음 function 기능이 아님
print(t[:,1])
print(t[:,1].size())
print(t[:,:-1])

2 torch.Size([4, 3]) torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


# Broadcasting

In [11]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [12]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])
print(m1+m2)

tensor([[4., 5.]])


In [13]:
m1 = torch.FloatTensor([[1,2]]) #1x2 -> 2x2
m2 = torch.FloatTensor([[3],[4]]) # 2x1 -> 2x2
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


# Multiplication vs Matrix Multiplication

In [14]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print(m1.shape)
print(m2.shape)
print(m1.matmul(m2))

torch.Size([2, 2])
torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [15]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print(m1.shape)
print(m2.shape)
print(m1*m2) #m1:2x2 ,m2:2x1-> 2x2
print(m1.matmul(m2))

torch.Size([2, 2])
torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[ 5.],
        [11.]])


# Mean

In [16]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [17]:
# In Integer can't use mean()
t = torch.LongTensor([1,2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [18]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [19]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


# Sum

In [20]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [21]:
print(t.sum())
print(t.sum(dim=0)) #행방향 -> 세로 방향
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


# Max and Argmax

In [22]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [23]:
print(t.max())

tensor(4.)


In [24]:
print(t.max(dim=0))
print(t.max(dim=0)[0])
print(t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
tensor([3., 4.])
tensor([1, 1])


In [25]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
