In [3]:
import tensorflow as tf
import numpy as np
from tensorflow.contrib import rnn
import pprint
pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [2]:
# One hot encoding for each char in 'hello'
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

# 1. 단순 cell & RNN구동

In [6]:
with tf.variable_scope('one_cell') as scope:
    hidden_size=2
    cell=tf.contrib.rnn.BasicRNNCell(num_units=hidden_size)
    print(cell.output_size, cell.state_size)
    
    x_data=np.array([[h]],dtype=np.float32)
    pp.pprint(x_data)
    outputs, _states=tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
    
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

2 2
array([[[1., 0., 0., 0.]]], dtype=float32)
array([[[-0.5416666 ,  0.46519306]]], dtype=float32)


In [7]:
with tf.variable_scope('two_sequence') as scope:
    hidden_size=2
    cell=tf.contrib.rnn.BasicRNNCell(num_units=hidden_size)
    x_data=np.array([[h,e,l,l,o]],dtype=np.float32)
    print(x_data.shape)
    pp.pprint(x_data)
    outputs, _states=tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

(1, 5, 4)
array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]], dtype=float32)
array([[[ 0.63252926,  0.42558262],
        [ 0.4365432 ,  0.5447821 ],
        [ 0.28750902,  0.1947609 ],
        [ 0.37134635,  0.06284075],
        [-0.61012554, -0.5030448 ]]], dtype=float32)


In [10]:
with tf.variable_scope('3_batches') as scope:
    x_data=np.array([[h,e,l,l,o],
                    [e,o,l,l,l],
                    [l,l,e,e,l]], dtype=np.float32)
    pp.pprint(x_data)
    
    hidden_size=2
    #cell=tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size, state_is_tuple=True)
    cell=tf.nn.rnn_cell.LSTMCell(num_units=hidden_size, state_is_tuple=True)
    outputs, _states = tf.nn.dynamic_rnn(cell,x_data,dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())    

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]],

       [[0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.]],

       [[0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]], dtype=float32)
array([[[-0.02717627,  0.10343352],
        [-0.05944539, -0.06865926],
        [ 0.079931  , -0.05383695],
        [ 0.19126518, -0.03395795],
        [ 0.03669601, -0.13939026]],

       [[-0.04529956, -0.1230847 ],
        [-0.09512901, -0.22630163],
        [ 0.03114672, -0.12730424],
        [ 0.15569067, -0.08464055],
        [ 0.24332023, -0.05231608]],

       [[ 0.13304685,  0.00085444],
        [ 0.2285104 ,  0.00498608],
        [ 0.11795559, -0.12232529],
        [ 0.03877641, -0.19444795],
        [ 0.16484462, -0.14642125]]], dtype=float32)
