In [27]:
import pandas as pd
data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'
df_data=pd.read_csv(data_url, sep='\s+', header=None)
df_data.columns=['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT','MEDV']
#14개 항목의 feature 이름을 지을 수 있다.
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [8]:
import numpy as np
weight_vector = np.array([[1],[1],[1]])
x_vector=np.array([[3],[4],[5]])
weight_vector.T.dot(x_vector)

array([[12]])

In [11]:
a=[1,2,3]
a
b=[[1],[2],[3]]
b

[[1], [2], [3]]

In [17]:
c=np.array([1,2,3])
d=np.array([[1],[2],[3]])
c.dot(d)

array([14])

In [18]:
df_data.as_matrix()

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 3.9690e+02, 4.9800e+00,
        2.4000e+01],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 3.9690e+02, 9.1400e+00,
        2.1600e+01],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 3.9283e+02, 4.0300e+00,
        3.4700e+01],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 5.6400e+00,
        2.3900e+01],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 3.9345e+02, 6.4800e+00,
        2.2000e+01],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 7.8800e+00,
        1.1900e+01]])

In [20]:
df_data.shape

(506, 14)

In [21]:
import numpy as np
weight_vector = np.array([[1],[1],[1]])
x_vector=np.array([[3],[4],[5]])
weight_vector.T.dot(x_vector)

array([[12]])

In [23]:
df_data.values[0]

array([6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
       6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
       4.980e+00, 1.000e+00])

In [30]:
df_data['weight_0']=1
df_data

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD    TAX  \
0     0.00632  18.0   2.31     0  0.538  6.575   65.2  4.0900    1  296.0   
1     0.02731   0.0   7.07     0  0.469  6.421   78.9  4.9671    2  242.0   
2     0.02729   0.0   7.07     0  0.469  7.185   61.1  4.9671    2  242.0   
3     0.03237   0.0   2.18     0  0.458  6.998   45.8  6.0622    3  222.0   
4     0.06905   0.0   2.18     0  0.458  7.147   54.2  6.0622    3  222.0   
5     0.02985   0.0   2.18     0  0.458  6.430   58.7  6.0622    3  222.0   
6     0.08829  12.5   7.87     0  0.524  6.012   66.6  5.5605    5  311.0   
7     0.14455  12.5   7.87     0  0.524  6.172   96.1  5.9505    5  311.0   
8     0.21124  12.5   7.87     0  0.524  5.631  100.0  6.0821    5  311.0   
9     0.17004  12.5   7.87     0  0.524  6.004   85.9  6.5921    5  311.0   
10    0.22489  12.5   7.87     0  0.524  6.377   94.3  6.3467    5  311.0   
11    0.11747  12.5   7.87     0  0.524  6.009   82.9  6.2267    5  311.0   
12    0.09378  12.5   7.87     0  0.524  5.889   39.0  5.4509    5  311.0   
13    0.62976   0.0   8.14     0  0.538  5.949   61.8  4.7075    4  307.0   
14    0.63796   0.0   8.14     0  0.538  6.096   84.5  4.4619    4  307.0   
15    0.62739   0.0   8.14     0  0.538  5.834   56.5  4.4986    4  307.0   
16    1.05393   0.0   8.14     0  0.538  5.935   29.3  4.4986    4  307.0   
17    0.78420   0.0   8.14     0  0.538  5.990   81.7  4.2579    4  307.0   
18    0.80271   0.0   8.14     0  0.538  5.456   36.6  3.7965    4  307.0   
19    0.72580   0.0   8.14     0  0.538  5.727   69.5  3.7965    4  307.0   
20    1.25179   0.0   8.14     0  0.538  5.570   98.1  3.7979    4  307.0   
21    0.85204   0.0   8.14     0  0.538  5.965   89.2  4.0123    4  307.0   
22    1.23247   0.0   8.14     0  0.538  6.142   91.7  3.9769    4  307.0   
23    0.98843   0.0   8.14     0  0.538  5.813  100.0  4.0952    4  307.0   
24    0.75026   0.0   8.14     0  0.538  5.924   94.1  4.3996    4  307.0   
25    0.84054   0.0   8.14     0  0.538  5.599   85.7  4.4546    4  307.0   
26    0.67191   0.0   8.14     0  0.538  5.813   90.3  4.6820    4  307.0   
27    0.95577   0.0   8.14     0  0.538  6.047   88.8  4.4534    4  307.0   
28    0.77299   0.0   8.14     0  0.538  6.495   94.4  4.4547    4  307.0   
29    1.00245   0.0   8.14     0  0.538  6.674   87.3  4.2390    4  307.0   
..        ...   ...    ...   ...    ...    ...    ...     ...  ...    ...   
476   4.87141   0.0  18.10     0  0.614  6.484   93.6  2.3053   24  666.0   
477  15.02340   0.0  18.10     0  0.614  5.304   97.3  2.1007   24  666.0   
478  10.23300   0.0  18.10     0  0.614  6.185   96.7  2.1705   24  666.0   
479  14.33370   0.0  18.10     0  0.614  6.229   88.0  1.9512   24  666.0   
480   5.82401   0.0  18.10     0  0.532  6.242   64.7  3.4242   24  666.0   
481   5.70818   0.0  18.10     0  0.532  6.750   74.9  3.3317   24  666.0   
482   5.73116   0.0  18.10     0  0.532  7.061   77.0  3.4106   24  666.0   
483   2.81838   0.0  18.10     0  0.532  5.762   40.3  4.0983   24  666.0   
484   2.37857   0.0  18.10     0  0.583  5.871   41.9  3.7240   24  666.0   
485   3.67367   0.0  18.10     0  0.583  6.312   51.9  3.9917   24  666.0   
486   5.69175   0.0  18.10     0  0.583  6.114   79.8  3.5459   24  666.0   
487   4.83567   0.0  18.10     0  0.583  5.905   53.2  3.1523   24  666.0   
488   0.15086   0.0  27.74     0  0.609  5.454   92.7  1.8209    4  711.0   
489   0.18337   0.0  27.74     0  0.609  5.414   98.3  1.7554    4  711.0   
490   0.20746   0.0  27.74     0  0.609  5.093   98.0  1.8226    4  711.0   
491   0.10574   0.0  27.74     0  0.609  5.983   98.8  1.8681    4  711.0   
492   0.11132   0.0  27.74     0  0.609  5.983   83.5  2.1099    4  711.0   
493   0.17331   0.0   9.69     0  0.585  5.707   54.0  2.3817    6  391.0   
494   0.27957   0.0   9.69     0  0.585  5.926   42.6  2.3817    6  391.0   
495   0.17899   0.0   9.69     0  0.585  5.670   28.8  2.7986    6  391.0   
496  

In [28]:
df_data=df_data.drop("MEDV", axis=1)

In [31]:
df_data.shape

(506, 14)

In [32]:
df_matrix=df_data.as_matrix()

In [33]:
weight_vector = np.random.rand

In [37]:
x=np.random.rand(10)
x

array([0.38936462, 0.91976421, 0.3222368 , 0.38251954, 0.58981674,
       0.69025693, 0.49741601, 0.64319154, 0.45798342, 0.69061967])

In [36]:
np.random.randint(10)

3

In [40]:
y=np.random.shuffle(x)
x

array([0.64319154, 0.45798342, 0.69061967, 0.69025693, 0.3222368 ,
       0.58981674, 0.49741601, 0.38936462, 0.38251954, 0.91976421])

In [43]:
np.random.choice(x, 6, replace=True, p=None)

array([0.49741601, 0.69025693, 0.45798342, 0.3222368 , 0.91976421,
       0.45798342])

In [49]:
x=np.random.randint(5,10,10)
x

array([9, 8, 8, 8, 8, 6, 5, 9, 8, 9])

In [51]:
c=np.random.seed(100)
c

In [52]:
np.unique(x)

array([5, 6, 8, 9])

In [55]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)
index

array(['a', 'b', 'c'], dtype='<U1')

In [56]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6)

array([0, 2, 3, 1, 0, 0], dtype=int64)

In [60]:
x=np.random.randint(1,7,10)
x

array([5, 5, 4, 4, 4, 2, 2, 6, 4, 1])

In [61]:
np.bincount(x, minlength=7)

array([0, 1, 2, 0, 4, 2, 1], dtype=int64)