In [11]:
import numpy as np

test_array=np.array(["1",4,5,8],float)

type(test_array) # numpy.float64 => float 64bit
type(test_array[1])

numpy.float64

In [12]:
test_array.shape


(4,)

In [13]:
test_array.dtype

dtype('float64')

In [15]:
tensor = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(tensor, int).shape

(4, 3, 4)

In [16]:
np.array(tensor, int).ndim

3

In [17]:
np.array(tensor, int).size

48

In [20]:
np.array([[1,2,3],[4.5,"5",6]],dtype=float)

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]])

In [21]:
np.array(tensor).reshape(12,4)

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [26]:
np.array(tensor).reshape(-1,3)


array([[1, 2, 5],
       [8, 1, 2],
       [5, 8, 1],
       [2, 5, 8],
       [1, 2, 5],
       [8, 1, 2],
       [5, 8, 1],
       [2, 5, 8],
       [1, 2, 5],
       [8, 1, 2],
       [5, 8, 1],
       [2, 5, 8],
       [1, 2, 5],
       [8, 1, 2],
       [5, 8, 1],
       [2, 5, 8]])

In [27]:
np.array(tensor).flatten()


array([1, 2, 5, 8, 1, 2, 5, 8, 1, 2, 5, 8, 1, 2, 5, 8, 1, 2, 5, 8, 1, 2,
       5, 8, 1, 2, 5, 8, 1, 2, 5, 8, 1, 2, 5, 8, 1, 2, 5, 8, 1, 2, 5, 8,
       1, 2, 5, 8])

In [51]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[6,7,8,9,10],[6,7,8,9,10]],int)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10]])

In [52]:
a[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [ 8,  9, 10],
       [ 8,  9, 10]])

In [46]:
a[1,1:3]

array([7, 8])

In [53]:
a[1:3]	#1 Row~2Row 전체

array([[ 6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10]])

In [54]:
a[2,::2]

array([ 6,  8, 10])

In [55]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [67]:
np.arange(0,5,0.5).reshape(-1,2)

array([[0. , 0.5],
       [1. , 1.5],
       [2. , 2.5],
       [3. , 3.5],
       [4. , 4.5]])

In [66]:
np.arange(30).reshape(-1,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [69]:
np.arange(30).reshape(5,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]]])

In [75]:
np.ones_like(np.arange(30).reshape(-1,5))

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [87]:
np.empty(shape=(4,3),dtype=float)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [88]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [89]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [90]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [92]:
np.eye(3,5,dtype=float)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [93]:
np.eye(3,5,2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [95]:
np.random.uniform(0,1,10).reshape(2,5) 

array([[0.58962851, 0.81863286, 0.61704221, 0.2585602 , 0.17566382],
       [0.97764352, 0.14059522, 0.9572501 , 0.09634967, 0.47587266]])

In [97]:
np.random.normal(0,0.05,10).reshape(2,5) 

array([[ 0.05624663, -0.03233334, -0.13314252,  0.00044747, -0.01111309],
       [ 0.03764788, -0.0466198 ,  0.00027834,  0.04831944, -0.06285941]])

In [123]:
test_array=np.arange(1,13).reshape(3,4) 
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [103]:

test_array.sum(axis=1), test_array.sum(axis=0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

In [113]:
third=np.array([test_array,test_array,test_array])
third

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [110]:
third.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [111]:
third.sum(axis=2).shape


(3, 3)

In [108]:
third.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [109]:
third.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [114]:
test_array.mean(axis=0)

array([5., 6., 7., 8.])

In [115]:
test_array.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [116]:
np.exp(test_array), np.sqrt(test_array)

(array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
        [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
        [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]]),
 array([[1.        , 1.41421356, 1.73205081, 2.        ],
        [2.23606798, 2.44948974, 2.64575131, 2.82842712],
        [3.        , 3.16227766, 3.31662479, 3.46410162]]))

In [124]:
third.mean(axis=0)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [139]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a,b

(array([1, 2, 3]), array([4, 5, 6]))

In [127]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [128]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [140]:
np.concatenate((a,b), axis=0)

array([1, 2, 3, 4, 5, 6])

In [136]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [2]:
import numpy as np
matrix_a=np.arange(1,13).reshape(3,4)
matrix_a*matrix_a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [3]:
test_a=np.arange(1,7).reshape(2,3)
test_b=np.arange(7,13).reshape(3,2)
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

In [5]:
test_matrix = np.array([[1,2,3],[4,5,6]],float)
scalar =3
test_matrix+scalar

array([[4., 5., 6.],
       [7., 8., 9.]])

In [6]:
a=np.arange(10)
np.any(a>5)

True

In [7]:
np.all(a>5)

False

In [9]:
sum(a>5)

4

In [13]:
test_a=np.array([1,3,0])
test_b=np.array([5,2,1])
test_a > test_b
(test_a > test_b).any()

True

In [14]:
np.logical_and(test_a>0, test_a<3)

array([ True, False, False])

In [15]:
b=np.array([True,False])
np.logical_not(b)

array([False,  True])

In [16]:
np.logical_or(test_a,test_b)

array([ True,  True,  True])

In [19]:
np.where(a>5)				#Index 값 반환
np.isnan(a)				#Not a Number

array([False, False, False, False, False, False, False, False, False,
       False])

In [20]:
np.isfinite(a)				#is finite number

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [22]:
np.Inf

inf

In [23]:
a=np.array([1,2,9,4,8,78,23,3])
np.argmax(a), np.argmin(a)

(5, 0)

In [30]:
a=a.reshape(-1,4)
a


array([[ 1,  2,  9,  4],
       [ 8, 78, 23,  3]])

In [29]:
np.argmax(a, axis=1)

array([2, 1], dtype=int64)

In [37]:
test_array= np.array([1,4,0,2,3,8,9,7])
condition=test_array>3
condition.astype(np.int)


array([0, 1, 0, 0, 0, 1, 1, 1])

In [34]:
test_array[condition]

array([4, 8, 9, 7])

In [38]:
a=np.array([2,4,6,8])
b=np.array([0,1,1,3,2,1])
a[b]	#bracket index, b 배열의 값을 index로 하여 a의 값 추출
a.take(b) #take 함수 , bracket index와 같은 효과

array([2, 4, 4, 8, 6, 4])

In [40]:
a=np.array([[1,4],[9,16]])
b=np.array([0,1,1,1])
a[b]

array([[ 1,  4],
       [ 9, 16],
       [ 9, 16],
       [ 9, 16]])